In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cars.csv')

In [4]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [13]:
# df['brand'].value_counts()
# df['brand'].nunique()
# df['fuel'].value_counts()
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

## 1. OneHotEncoding Using Pandas

In [14]:
pd.get_dummies(df, columns=['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

## K-1 HotEncoding

In [15]:
pd.get_dummies(df, columns=['fuel', 'owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

## OneHotEncoding Using Scikit-Learn

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2, random_state=0)

In [22]:
X_train.head()

         brand  km_driven    fuel         owner
3042   Hyundai      60000     LPG   First Owner
1520      Tata     150000  Diesel   Third Owner
2611   Hyundai     110000  Diesel  Second Owner
3544  Mahindra      28000  Diesel  Second Owner
4138    Maruti      15000  Petrol   First Owner

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [49]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype='int32')

In [50]:
X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']])

In [51]:
X_test_new = ohe.transform(X_test[['fuel', 'owner']])

In [52]:
X_train_new

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], shape=(6502, 7), dtype=int32)

In [53]:
np.hstack((X_train[['brand', 'km_driven']].values, X_train_new)).shape

(6502, 9)

## 4. OneHotEncoding with Top Categories

In [54]:
counts = df['brand'].value_counts()

In [55]:
df['brand'].nunique()
threshold=100

In [57]:
repl = counts[counts <=threshold].index

In [63]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
5697,0,0,0,0,0,0,0,0,0,1,0,0,0
1705,0,0,0,0,1,0,0,0,0,0,0,0,0
7072,0,0,0,0,0,0,0,0,0,0,0,1,0
6900,0,0,0,0,0,0,0,0,0,0,0,0,1
3824,0,0,0,0,1,0,0,0,0,0,0,0,0